name: Build

jobs:
  xcode:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup-xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.2
    - name: Configure Logger
      run: |
        sudo log config --mode "level:off"
        sudo log config --mode "level:debug" --subsystem com.apple.dt.xctest.tool
    - name: Test
      run: |
        xcodebuild build test -scheme log4swift-OSX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 9 * * 0,1,2,3,4'
